export const TOGGLE_DEV_TOOLS_SUCCESS = 'TOGGLE_DEV_TOOLS_SUCCESS';
export const OPEN_LOCAL_FOLDER_SUCCESS = 'OPEN_LOCAL_FOLDER_SUCCESS';
export const REFRESH_APP_SUCCESS = 'REFRESH_APP_SUCCESS';
export const WRITE_FILE = 'WRITE_FILE';
export const READ_FILE = 'READ_FILE';